version: "1"

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:
  # ---------------------------------------------------------------------------
  # Main application
  # ---------------------------------------------------------------------------

  chirpstack:
    container_name: chirpstack
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./chirpstack-certificates:/etc/chirpstack/certs
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - 8080:8080

  chirpstack-rest-api:
    container_name: chirpstack-api
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - 8090:8090
    depends_on:
      - chirpstack

  postgres:
    container_name: chirpstack-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - chirpstack-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root

  redis:
    container_name: chirpstack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - chirpstack-redis:/data

  mosquitto:
    container_name: chirpstack-mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./configuration/mosquitto:/mosquitto/config
      - ./chirpstack-certificates:/mosquitto/config/certs

  # ---------------------------------------------------------------------------
  # Certificate generator
  # ---------------------------------------------------------------------------

  chirpstack-certificates:
    container_name: chirpstack-certificates
    build:
      context: ./chirpstack-certificates
      dockerfile: Dockerfile-devel
    volumes:
      - ./chirpstack-certificates:/chirpstack-certificates/certs
    environment:
      - CHIRPSTACK_GATEWAY_BRIDGE_HOSTS=127.0.0.1,localhost
      - MQTT_BROKER_HOSTS=127.0.0.1,localhost
    command: make

  # ---------------------------------------------------------------------------
  # Bridges
  # ---------------------------------------------------------------------------

  chirpstack-gateway-bridge-udp:
    container_name: chirpstack-bridge-udp-as923_2
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
      - ./chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on:
      - mosquitto
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=as923_2/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=as923_2/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=as923_2/gateway/{{ .GatewayID }}/command/#

  chirpstack-gateway-bridge-basicstation:
    container_name: chirpstack-bridge-basicstation-as923_2
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-as923_2.toml
    ports:
      - 3001:3001
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
      - ./chirpstack-certificates:/etc/chirpstack-gateway-bridge/certs
    depends_on:
      - mosquitto
    environment:
      - BACKEND__BASIC_STATION__TLS_CERT=/etc/chirpstack-gateway-bridge/certs/chirpstack-gateway-bridge/basicstation/basicstation.pem
      - BACKEND__BASIC_STATION__TLS_KEY=/etc/chirpstack-gateway-bridge/certs/chirpstack-gateway-bridge/basicstation/basicstation-key.pem
      - BACKEND__BASIC_STATION__CA_CERT=/etc/chirpstack-gateway-bridge/certs/ca/ca.pem

# ---------------------------------------------------------------------------
# PERSISTENT VOLUMES
# ---------------------------------------------------------------------------

volumes:
  chirpstack-postgresql:
  chirpstack-redis:
